#!/bin/bash
echo "Deploying Linuse!"

# Descarga de repos
cd ..
git clone https://github.com/sisoputnfrba/so-commons-library.git
git clone https://github.com/sisoputnfrba/hilolay.git
git clone https://github.com/sisoputnfrba/linuse-tests-programs

# Instalacion de Commons
cd so-commons-library
make install

# Instalacion de la biblioteca de sockets
cd ../tp-2019-2c-Los-Borbotones/lib/sockets
make all

# Instalacion de hilolay
cd ../../../hilolay
make
make install

# Copia de archivos necesarios para tests
cp ../tp-2019-2c-Los-Borbotones/linuse-tests-files/Makefile ../linuse-tests-programs/Makefile

# Compilacion de linuse-tests-programs
cd ../linuse-tests-programs
make
make entrega

# Instalacion de la libreria libMUSE
#cd ../tp-2019-2c-Los-Borbotones/lib/libMUSE
#make all